name: Compile LaTeX CV to PDF

# Trigger the workflow when:
# 1. Any .tex file is pushed to main branch
# 2. Manual trigger from GitHub Actions tab
on:
  push:
    branches: [ main ]
    paths: 
      - '**/*.tex'
      - 'CV/**'
  workflow_dispatch:  # Allows manual triggering

jobs:
  compile-latex:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        # This ensures we can push back to the repo
        token: ${{ secrets.GITHUB_TOKEN }}
        
    # Install complete LaTeX environment
    - name: Install LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-full
        
    # Compile LaTeX with proper error handling
    - name: Compile LaTeX
      run: |
        cd CV
        echo "Starting XeLaTeX compilation..."
        xelatex -interaction=nonstopmode cv.tex
        
        # Check if compilation succeeded
        if [ $? -eq 0 ]; then
          echo "✅ First pass completed successfully"
        else
          echo "❌ First pass failed, showing errors:"
          cat cv.log
          exit 1
        fi
        
        # Second pass for references
        echo "Running second pass..."
        xelatex -interaction=nonstopmode cv.tex
        
    # Check if PDF was generated successfully
    - name: Check if PDF exists
      run: |
        if [ -f "CV/cv.pdf" ]; then
          echo "✅ PDF compiled successfully!"
          ls -la CV/cv.pdf
        else
          echo "❌ PDF compilation failed!"
          exit 1
        fi
        
    # Configure git for the GitHub Actions bot
    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
    # Commit and push the updated PDF if it changed
    - name: Commit updated PDF
      run: |
        git add CV/cv.pdf
        # Only commit if there are changes
        if git diff --staged --quiet; then
          echo "No changes to PDF, skipping commit"
        else
          git commit -m "🤖 Auto-compile LaTeX CV to PDF
          
          Automatically compiled CV/cv.tex to CV/cv.pdf
          
          Generated by GitHub Actions on $(date)"
          git push
          echo "✅ Updated PDF committed and pushed!"
        fi
        
    # Upload PDF as artifact (optional - for downloading from Actions tab)
    - name: Upload PDF artifact
      uses: actions/upload-artifact@v4
      with:
        name: compiled-cv-pdf
        path: CV/cv.pdf
        retention-days: 30